# Generated by Django 5.2.17 on 2026-08-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0003_property_tin_number_property_tot_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('food_beverage', 'Food & Beverage / Restaurant'), ('laundry', 'Laundry Service'), ('transport', 'Airport Transfer / Shuttle'), ('facility', 'Facility / Extra Bed'), ('other', 'Other Service')], default='food_beverage', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='properties.property')),
            ],
        ),
    ]
