# Generated by Django 5.2.17 on 2026-08-11 09:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', '🛠️ Maintenance & Repairs'), ('utilities', '⚡ Utilities & Fuel'), ('supplies', '🧹 Housekeeping & Cleaning Supplies'), ('amenities', '🍱 Amenities & Guest Supplies'), ('payroll', '💼 Salaries & Staff Wages'), ('taxes', '🏛️ Taxes & Government Licensing'), ('other', '📦 Other Operational Expense')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('paid_to', models.CharField(blank=True, help_text='Vendor / Recipient Name', max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash Drawer'), ('bank_transfer', 'Bank Transfer (CBE / Dashen / Awash)'), ('telebirr', 'Telebirr'), ('cbe_birr', 'CBE Birr'), ('other', 'Other')], default='cash', max_length=30)),
                ('receipt_reference', models.CharField(blank=True, help_text='Invoice or Receipt #', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maintenance_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='maintenance.maintenanceticket')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='e.g. August 2026', max_length=50)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income Tax / Pension', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft / Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='properties.property')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present 🟢'), ('absent', 'Absent 🔴'), ('half_day', 'Half Day 🟡'), ('late', 'Late ⏳'), ('leave', 'On Leave 🏖️')], default='present', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='properties.property')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff_member', 'date')},
            },
        ),
    ]
