# Generated by Django 5.2.17 on 2026-08-11 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffattendance',
            options={'ordering': ['-date', 'staff_member']},
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
