# Generated by Django 5.2.17 on 2026-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('investor', 'Investor / Owner'), ('accountant', 'Finance / Accountant'), ('receptionist', 'Front Desk Receptionist'), ('guest', 'Guest / Customer')], default='guest', max_length=20),
        ),
    ]
