# Generated by Django 5.2.17 on 2026-08-11 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertystaff',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base monthly salary in ETB', max_digits=10),
        ),
    ]
