# Generated by Django 5.2.17 on 2026-08-11 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertystaff_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax Identification Number (TIN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tot_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Turnover Tax (TOT) % e.g. 2.00 or 10.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Value Added Tax (VAT) % e.g. 15.00', max_digits=5),
        ),
    ]
