# Generated by Django 5.2.17 on 2026-08-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('properties', '0003_property_tin_number_property_tot_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='guest',
            name='id_photo',
            field=models.FileField(blank=True, help_text='Photo / Scan of Guest ID or Passport', null=True, upload_to='guest_ids/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Primary property associated with this guest record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_document_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['full_name', 'phone_number'], name='guests_gues_full_na_cbca00_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['id_document_number'], name='guests_gues_id_docu_e3dea2_idx'),
        ),
    ]
