# Generated by Django 5.2.17 on 2026-08-09 20:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubscription',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertysubscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly (30 Days)'), ('3_months', '3 Months (90 Days)'), ('6_months', '6 Months (180 Days)'), ('annual', 'Annual (365 Days)')], default='annual', max_length=20),
        ),
    ]
